### ISSUE TITLE
Emily's texture

### ISSUE THREAD

**Issue by pointyteeth** [CNM190/Nightmare#28] opened 2015-02-27 23:29 UTC
* try increasing and decreasing "stroke-y-ness" to work with Renderman
* fix blush color
* freckle stretching on nose
* hair texture

**Comment by mark-craig** [comment] 2015-02-28 20:19
Recommend painting the hair texture in mudbox. Use the projection paint tool with a stencil ^^

**Comment by pointyteeth** [comment] 2015-03-02 04:27
Technically I did everything in this issue, but we're still trying to make the texture play nice with RenderMan, so... I'd like to keep it open:
* make the texture look good with renderman
* apply that to the hair and body
* edit displacement and other maps?

**Comment by mark-craig** [comment] 2015-03-02 20:26
Hmm. I'm tempted to say that since most of this will need to be done in Mudbox, maybe someone else should keep pushing on this since you're already working on learning NUKE (or vice versa). Unless you feel comfortable with Mudbox,  I think asking you to try to learn two programs within a couple weeks might be a bit much.

**Comment by pointyteeth** [comment] 2015-03-03 07:02
Er. Is Mudbox hard to pick up? Also, I feel like I've been doing fine with just Photoshop, from what I've read Mudbox is mainly useful for getting seams right (although I've never used it so I don't know lol). Texturing has been really fun, so i'd like to stay with it... But, if someone else wants to join me on #TextureTeam I'd be down :)

**Comment by mark-craig** [comment] 2015-03-03 17:00
Well, the color map is mostly done. The problem is the bump/specularity map. Very impractical to do in photoshop without a plugin like this one: http://quixel.se/dev/ddo. That is a very good alternative to Mudbox if you'd rather use that. Otherwise I will take a crack at it soon.

**Comment by pointyteeth** [comment] 2015-03-03 18:04
Ah, okay, Yeah, I think I can figure that out, thanks for letting me know about that plugin!

**Comment by mark-craig** [comment] 2015-03-03 19:18
Ah, I'm fixing the file references in the Emily2015 file, and it seems like @SaraSweer has already made a specularity map! I'm not sure if the specularity should be affected by the skin pores or not, but if we make a separate map for that we should consolidate the two.

**Comment by SaraSweer** [comment] 2015-03-04 06:00
The specularity map is mapped to specular roughness not specular gain so
that should not have texture mapping on it. A seperate bump map or specular
gain texture might work. Also I will be moving on to the hair texture as
soon as I finish the eyes.

**Comment by mark-craig** [comment] 2015-03-10 03:42
Marking as closed. Meena, feel free to add additional details such as the thingy below the nostrils or lip creases, but honestly it looks good enough that this is no longer a priority (not as big as the hair anyway).

**Closed by mark-craig** 2015-03-10 03:42 UTC
